title: "BomberFish's Blog"
author: "BomberFish"
description: "Various ramblings"

email: "hariz@bomberfish.ca"
github_username: "BomberFish"
youtube_username: "@bomberfish77"
twitter_username: "bomberfish77"

mastodon:
 - username: "fish@wetdry.world"
   instance: "wetdry.world"

theme: "minima"

rss: rss

kramdown:
  syntax_highlighter: rouge
  math_engine: mathjax

plugins:
  - jekyll-feed
  - jekyll-sitemap

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: [Other]

minima:
  show_excerpts: true
  social_links:
    github: "BomberFish"
    youtube: "@bombardierfish"
    rss: rss
    mastodon:
     - username: "fish@wetdry.world"
       instance: "wetdry.world"
